import type { MetadataRoute } from "next";

/**
 * robots.txt — generated by Next.js at /robots.txt.
 *
 * Allow all crawlers everywhere except the dynamic OG image endpoints
 * (no SEO value, and crawling them wastes serverless invocations).
 * Points to the sitemap for discovery.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: ["/api/", "/q-shield/compare/opengraph-image"],
    },
    sitemap: "https://qadvantage.io/sitemap.xml",
    host: "https://qadvantage.io",
  };
}
