import type { MetadataRoute } from "next";
import { getLatestRun } from "@/lib/data/load";

/**
 * sitemap.xml — generated by Next.js at /sitemap.xml.
 *
 * Lists every indexable page. Algorithm detail pages are derived from the
 * latest run so the sitemap stays accurate as the algorithm set evolves.
 * OG image routes and API routes are intentionally excluded (no SEO value).
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://qadvantage.io";
  const run = getLatestRun();
  // Use the latest run's timestamp as lastModified for data-driven pages.
  const dataLastMod = run.timestamp;

  const staticPages: MetadataRoute.Sitemap = [
    {
      url: base,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${base}/q-shield`,
      lastModified: dataLastMod,
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: `${base}/q-shield/compare`,
      lastModified: dataLastMod,
      changeFrequency: "daily",
      priority: 0.7,
    },
    {
      url: `${base}/pqc-arena`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${base}/pqc-arena/policy`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${base}/methodology`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.6,
    },
  ];
  // NOTE: /q-day-index and /q-shield/protocols are live but absent from this
  // list — a pre-existing gap, not introduced here. Left alone deliberately
  // rather than silently widening this change's scope.

  const algorithmPages: MetadataRoute.Sitemap = run.algorithms.map((a) => ({
    url: `${base}/q-shield/${a.id}`,
    lastModified: dataLastMod,
    changeFrequency: "daily" as const,
    priority: 0.6,
  }));

  return [...staticPages, ...algorithmPages];
}
